steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/warehouse-backend:$COMMIT_SHA',
        '.',
      ]
    dir: 'server'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/warehouse-backend:$COMMIT_SHA',
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy warehouse-backend \
          --region=europe-west2 \
          --image=europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/warehouse-backend:$COMMIT_SHA \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --set-env-vars=NODE_ENV=production \
          --set-secrets=DATABASE_URL=warehouse-database-url:latest,JWT_SECRET=warehouse-jwt-secret:latest \
          --add-cloudsql-instances=checkout-tracking-app:europe-west2:store-migration-db

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/warehouse-backend:$COMMIT_SHA'
